import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import './globals.css'

const inter = Inter({
    weight: ['400', '500', '600'],
    subsets: ['latin'],
});

export const metadata = {
    title: "MyApp",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={inter.className}>
        {children}
        <Toaster position="bottom-right"/>
        </body>
        </html>
    );
}


