import { Inter } from "next/font/google";
import '../globals.css'
import AdminSidebar from "../../components/admin/AdminSidebar";
import HeaderWrapper from "../../utils/HeaderWrapper";

const inter = Inter({
    weight: ['400', '500', '600'],
    subsets: ['latin'],
});

export const metadata = {
    title: "MyApp",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <div className="flex flex-row bg-custom-gray h-screen">
            <AdminSidebar/>
            <div className="flex-1">
                <HeaderWrapper />
                {children}
            </div>
        </div>
    );
}
